commitdev/terraform-aws-zero

- modules/sendgrid/README.md
- modules/sendgrid/main.tf
- modules/sendgrid/sendgrid-external-datasource.sh
- modules/sendgrid/variables.tf
> sendgrid domain authentication support

- modules/certificate/README.md
- modules/certificate/main.tf
- modules/certificate/variables.tf
https://app.zenhub.com/workspaces/commit-zero-5da8decc7046a60001c6db44/issues/commitdev/zero/235
> misc: zero-235 Document Hosting Support

- modules/database/outputs.tf
> fix: modules with count to pick index first item

- README.md
Adding a badge to the readme but also testing codeowners.
> chore: Add validation badge to readme

- modules/user_access/main.tf
> no prefix for user

- modules/s3_hosting/README.md
- modules/s3_hosting/main.tf
- modules/s3_hosting/variables.tf
> improvement: s3_hosting config for CORS origin

- modules/cloudtrail/README.md
- modules/cloudtrail/main.tf
- modules/cloudtrail/outputs.tf
- modules/cloudtrail/variables.tf
- modules/cloudtrail/versions.tf
> initial cloudtrail module commit

- modules/user_access/main.tf
- [-] README.md has been updated after any changes to variables and outputs. See https://github.com/commitdev/terraform-aws-zero/#doc-generation
> replace index with map

- modules/cloudtrail/main.tf
- modules/s3_hosting/main.tf
- [-] README.md has been updated after any changes to variables and outputs. See https://github.com/commitdev/terraform-aws-zero/#doc-generation
> add S3 encryption for modules s3_hosting and cloudtrail

- modules/cloudtrail/README.md
- modules/cloudtrail/main.tf
- modules/cloudtrail/variables.tf
- [- ] README.md has been updated after any changes to variables and outputs. See https://github.com/commitdev/terraform-aws-zero/#doc-generation
> 140 refine cloudtrail without environment as input

- modules/vpc/main.tf
> Added public/private visibility tags to subnets

- LICENSE
- LICENSE.info
- LICENSE.spdx
> Adds licensing information

- modules/user_access/main.tf
> fix: Dependency was missing between users and groups for group membership, causing membership addition to fail

- modules/sendgrid/README.md
- modules/sendgrid/variables.tf
- modules/user_access/main.tf
> improvement: remove sendgrid mail. domain prefix

- .github/workflows/terraform.yml
- CHANGELOG.md
- modules/vpc/README.md
- modules/vpc/main.tf
- modules/vpc/variables.tf
- add NAT instance creation in VPC module
- enable S3 service endpoint for same zone
ref: section - Best practice when sending traffic to Amazon S3 or DynamoDB in the same Region - https://docs.aws.amazon.com/vpc/latest/userguide/vpc-nat-gateway.html
> 166 nat instance

- modules/cache/README.md
- modules/cache/main.tf
- modules/cache/outputs.tf
- modules/cache/variables.tf
> 167 add cache

- modules/s3_hosting/README.md
- modules/s3_hosting/main.tf
- modules/s3_hosting/variables.tf
Added a variable that accepts and sets  the s3 lambda config block `lambda_function_association`
> Accept lambda configuration

- .github/workflows/terraform.yml
- modules/database/main.tf
- modules/logging/README.md
- modules/logging/main.tf
- modules/logging/variables.tf
- modules/s3_hosting/README.md
- modules/user_auth/README.md
- modules/user_auth/files/kratos-values.yml
- modules/user_auth/files/oathkeeper-values.yml
- modules/user_auth/files/oathkeeper_kratos_proxy_rules.yaml.tpl
- modules/user_auth/main.tf
- modules/user_auth/variables.tf
> User auth module with ORY Oathkeeper and Kratos

- modules/logging/main.tf
- modules/secret/README.md
- modules/secret/variables.tf
- modules/user_auth/README.md
- modules/user_auth/main.tf
- modules/user_auth/variables.tf
- modules/vpc/README.md
- modules/vpc/variables.tf
> Optional auth namespace creation

- modules/logging/README.md
- modules/logging/main.tf
- modules/logging/variables.tf
> change elasticseach force https default

- modules/user_auth/README.md
- modules/user_auth/main.tf
- modules/user_auth/variables.tf
> customizable helm resource name for multiple inst

- modules/cache/README.md
- modules/cache/variables.tf
- modules/database/README.md
- modules/database/variables.tf
- modules/ecr/README.md
- modules/ecr/variables.tf
- modules/eks/README.md
- modules/eks/variables.tf
- modules/kubernetes/ingress_nginx/README.md
- modules/kubernetes/ingress_nginx/main.tf
- modules/kubernetes/ingress_nginx/variables.tf
- modules/logging/README.md
- modules/logging/main.tf
- modules/logging/variables.tf
- modules/s3_hosting/README.md
- modules/s3_hosting/variables.tf
- modules/user_access/README.md
- modules/user_access/variables.tf
- modules/vpc/README.md
- modules/vpc/variables.tf
- chore: small documentation text changes
- enhancement: Moved nginx ingress creation from aws-eks module and converted to a helm chart. Also switched to using NLB instead of ELB.
> add nginx ingress module

- modules/kubernetes/ingress_nginx/main.tf
> fix: Oops, somehow this change got lost. Set ingress traffic policy to local to preserve source ip.

- modules/eks/main.tf
> chore: bump eks version to support 1.20

- modules/user_access/main.tf
> fix: Comparison in user_access module was not working correctly

- modules/eks/README.md
- modules/eks/main.tf
- modules/eks/variables.tf
> feat: Add support for eks addons for vpc cni, kube-proxy, coredns

- CHANGELOG.md
- modules/eks/main.tf
- chore: update changelog
- fix: Added dependency betweek eks addon and cluster
> add eks addon dependency

- modules/user_auth/README.md
- modules/user_auth/main.tf
- modules/user_auth/variables.tf
> improvement: allow overriding default config

- modules/user_auth/files/oathkeeper_kratos_proxy_rules.yaml.tpl
> fix: add user-auth verification form url

- modules/user_auth/README.md
- modules/user_auth/main.tf
- modules/user_auth/variables.tf
> improvement: user-auth add var for ory images tags

- modules/database/README.md
- modules/database/main.tf
- modules/database/outputs.tf
- modules/database/variables.tf
> feat: make db version configurable. Adds some required fields to the module

- modules/database/README.md
- modules/database/main.tf
- modules/database/outputs.tf
> feat: output security group id from the database module

- .pre-commit-config.yaml
- modules/database/README.md
- modules/database/main.tf
- modules/database/variables.tf
> database: support multi-az
